/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class Agent extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "accountId" })
    accountId: string;

    /**
     * The number of credits the agent has available. Credits can be negative if funds have been overdrawn.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "credits" })
    credits: number;

    /**
     * The headquarters of the agent.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "headquarters" })
    headquarters: string;

    /**
     * The faction the agent started with.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "startingFaction" })
    startingFaction: string;

    @SpeakeasyMetadata()
    @Expose({ name: "symbol" })
    symbol: string;
}
