/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Transform } from "class-transformer";

/**
 * The chart of a system or waypoint, which makes the location visible to other agents.
 */
export class Chart extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "submittedBy" })
    submittedBy?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "submittedOn" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    submittedOn?: Date;

    @SpeakeasyMetadata()
    @Expose({ name: "waypointSymbol" })
    waypointSymbol?: string;
}
