/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { SystemType } from "./systemtype";
import { Expose } from "class-transformer";

export class ConnectedSystem extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "distance" })
    distance: number;

    /**
     * The symbol of the faction that owns the connected jump gate in the system.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "factionSymbol" })
    factionSymbol?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "sectorSymbol" })
    sectorSymbol: string;

    @SpeakeasyMetadata()
    @Expose({ name: "symbol" })
    symbol: string;

    /**
     * The type of waypoint.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type: SystemType;

    @SpeakeasyMetadata()
    @Expose({ name: "x" })
    x: number;

    @SpeakeasyMetadata()
    @Expose({ name: "y" })
    y: number;
}
