/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * The details of a delivery contract. Includes the type of good, units needed, and the destination.
 */
export class ContractDeliverGood extends SpeakeasyBase {
    /**
     * The destination where goods need to be delivered.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "destinationSymbol" })
    destinationSymbol: string;

    /**
     * The symbol of the trade good to deliver.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "tradeSymbol" })
    tradeSymbol: string;

    /**
     * The number of units fulfilled on this contract.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "unitsFulfilled" })
    unitsFulfilled: number;

    /**
     * The number of units that need to be delivered on this contract.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "unitsRequired" })
    unitsRequired: number;
}
