/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class ExtractionYield extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "symbol" })
    symbol: string;

    /**
     * The number of units extracted that were placed into the ship's cargo hold.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "units" })
    units: number;
}
