/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ExtractionYield } from "./extractionyield";
import { Expose, Type } from "class-transformer";

export class Extraction extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "shipSymbol" })
    shipSymbol: string;

    @SpeakeasyMetadata()
    @Expose({ name: "yield" })
    @Type(() => ExtractionYield)
    yield: ExtractionYield;
}
