/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { FactionTrait } from "./factiontrait";
import { Expose, Type } from "class-transformer";

export class Faction extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description: string;

    @SpeakeasyMetadata()
    @Expose({ name: "headquarters" })
    headquarters: string;

    /**
     * Whether or not the faction is currently recruiting new agents.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "isRecruiting" })
    isRecruiting: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    @SpeakeasyMetadata()
    @Expose({ name: "symbol" })
    symbol: string;

    @SpeakeasyMetadata({ elemType: FactionTrait })
    @Expose({ name: "traits" })
    @Type(() => FactionTrait)
    traits: FactionTrait[];
}
