/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ConnectedSystem } from "./connectedsystem";
import { Expose, Type } from "class-transformer";

export class JumpGate extends SpeakeasyBase {
    /**
     * The systems within range of the gate that have a corresponding gate.
     */
    @SpeakeasyMetadata({ elemType: ConnectedSystem })
    @Expose({ name: "connectedSystems" })
    @Type(() => ConnectedSystem)
    connectedSystems: ConnectedSystem[];

    /**
     * The symbol of the faction that owns the gate.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "factionSymbol" })
    factionSymbol?: string;

    /**
     * The maximum jump range of the gate.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "jumpRange" })
    jumpRange: number;
}
