/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * A rough estimate of the total supply of this good in the marketplace.
 */
export enum MarketTradeGoodSupply {
    Scarce = "SCARCE",
    Limited = "LIMITED",
    Moderate = "MODERATE",
    Abundant = "ABUNDANT",
}

export class MarketTradeGood extends SpeakeasyBase {
    /**
     * The price at which this good can be purchased from the market.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "purchasePrice" })
    purchasePrice: number;

    /**
     * The price at which this good can be sold to the market.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "sellPrice" })
    sellPrice: number;

    /**
     * A rough estimate of the total supply of this good in the marketplace.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "supply" })
    supply: MarketTradeGoodSupply;

    /**
     * The symbol of the trade good.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "symbol" })
    symbol: string;

    /**
     * The typical volume flowing through the market for this type of good. The larger the trade volume, the more stable prices will be.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "tradeVolume" })
    tradeVolume: number;
}
