/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class Meta extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "limit" })
    limit: number;

    @SpeakeasyMetadata()
    @Expose({ name: "page" })
    page: number;

    @SpeakeasyMetadata()
    @Expose({ name: "total" })
    total: number;
}
