/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ShipNav } from "./shipnav";
import { ShipRegistration } from "./shipregistration";
import { Expose, Type } from "class-transformer";

/**
 * The engine of the ship.
 */
export class ScannedShipEngine extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "symbol" })
    symbol: string;
}

/**
 * The frame of the ship.
 */
export class ScannedShipFrame extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "symbol" })
    symbol: string;
}

/**
 * A mount on the ship.
 */
export class ScannedShipMounts extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "symbol" })
    symbol: string;
}

/**
 * The reactor of the ship.
 */
export class ScannedShipReactor extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "symbol" })
    symbol: string;
}

/**
 * The ship that was scanned. Details include information about the ship that could be detected by the scanner.
 */
export class ScannedShip extends SpeakeasyBase {
    /**
     * The engine of the ship.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "engine" })
    @Type(() => ScannedShipEngine)
    engine: ScannedShipEngine;

    /**
     * The frame of the ship.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "frame" })
    @Type(() => ScannedShipFrame)
    frame?: ScannedShipFrame;

    @SpeakeasyMetadata({ elemType: ScannedShipMounts })
    @Expose({ name: "mounts" })
    @Type(() => ScannedShipMounts)
    mounts?: ScannedShipMounts[];

    /**
     * The navigation information of the ship.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "nav" })
    @Type(() => ShipNav)
    nav: ShipNav;

    /**
     * The reactor of the ship.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "reactor" })
    @Type(() => ScannedShipReactor)
    reactor?: ScannedShipReactor;

    /**
     * The public registration information of the ship
     */
    @SpeakeasyMetadata()
    @Expose({ name: "registration" })
    @Type(() => ShipRegistration)
    registration: ShipRegistration;

    /**
     * The globally unique identifier of the ship.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "symbol" })
    symbol: string;
}
