/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { WaypointType } from "./waypointtype";
import { Expose } from "class-transformer";

/**
 * The destination or departure of a ships nav route.
 */
export class ShipNavRouteWaypoint extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "symbol" })
    symbol: string;

    @SpeakeasyMetadata()
    @Expose({ name: "systemSymbol" })
    systemSymbol: string;

    /**
     * The type of waypoint.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type: WaypointType;

    @SpeakeasyMetadata()
    @Expose({ name: "x" })
    x: number;

    @SpeakeasyMetadata()
    @Expose({ name: "y" })
    y: number;
}
