/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ShipRequirements } from "./shiprequirements";
import { Expose, Type } from "class-transformer";

export enum ShipMountDeposits {
    QuartzSand = "QUARTZ_SAND",
    SiliconCrystals = "SILICON_CRYSTALS",
    PreciousStones = "PRECIOUS_STONES",
    IceWater = "ICE_WATER",
    AmmoniaIce = "AMMONIA_ICE",
    IronOre = "IRON_ORE",
    CopperOre = "COPPER_ORE",
    SilverOre = "SILVER_ORE",
    AluminumOre = "ALUMINUM_ORE",
    GoldOre = "GOLD_ORE",
    PlatinumOre = "PLATINUM_ORE",
    Diamonds = "DIAMONDS",
    UraniteOre = "URANITE_ORE",
    MeritiumOre = "MERITIUM_ORE",
}

export enum ShipMountSymbol {
    MountGasSiphonI = "MOUNT_GAS_SIPHON_I",
    MountGasSiphonIi = "MOUNT_GAS_SIPHON_II",
    MountGasSiphonIii = "MOUNT_GAS_SIPHON_III",
    MountSurveyorI = "MOUNT_SURVEYOR_I",
    MountSurveyorIi = "MOUNT_SURVEYOR_II",
    MountSurveyorIii = "MOUNT_SURVEYOR_III",
    MountSensorArrayI = "MOUNT_SENSOR_ARRAY_I",
    MountSensorArrayIi = "MOUNT_SENSOR_ARRAY_II",
    MountSensorArrayIii = "MOUNT_SENSOR_ARRAY_III",
    MountMiningLaserI = "MOUNT_MINING_LASER_I",
    MountMiningLaserIi = "MOUNT_MINING_LASER_II",
    MountMiningLaserIii = "MOUNT_MINING_LASER_III",
    MountLaserCannonI = "MOUNT_LASER_CANNON_I",
    MountMissileLauncherI = "MOUNT_MISSILE_LAUNCHER_I",
    MountTurretI = "MOUNT_TURRET_I",
}

/**
 * A mount is installed on the exterier of a ship.
 */
export class ShipMount extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "deposits" })
    deposits?: ShipMountDeposits[];

    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    /**
     * The requirements for installation on a ship
     */
    @SpeakeasyMetadata()
    @Expose({ name: "requirements" })
    @Type(() => ShipRequirements)
    requirements: ShipRequirements;

    @SpeakeasyMetadata()
    @Expose({ name: "strength" })
    strength?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "symbol" })
    symbol: ShipMountSymbol;
}
