/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ShipNavRouteWaypoint } from "./shipnavroutewaypoint";
import { Expose, Transform, Type } from "class-transformer";

/**
 * The routing information for the ship's most recent transit or current location.
 */
export class ShipNavRoute extends SpeakeasyBase {
    /**
     * The date time of the ship's arrival. If the ship is in-transit, this is the expected time of arrival.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "arrival" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    arrival: Date;

    /**
     * The destination or departure of a ships nav route.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "departure" })
    @Type(() => ShipNavRouteWaypoint)
    departure: ShipNavRouteWaypoint;

    /**
     * The date time of the ship's departure.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "departureTime" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    departureTime: Date;

    /**
     * The destination or departure of a ships nav route.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "destination" })
    @Type(() => ShipNavRouteWaypoint)
    destination: ShipNavRouteWaypoint;
}
