/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ShipCargo } from "./shipcargo";
import { ShipCrew } from "./shipcrew";
import { ShipEngine } from "./shipengine";
import { ShipFrame } from "./shipframe";
import { ShipFuel } from "./shipfuel";
import { ShipModule } from "./shipmodule";
import { ShipMount } from "./shipmount";
import { ShipNav } from "./shipnav";
import { ShipReactor } from "./shipreactor";
import { ShipRegistration } from "./shipregistration";
import { Expose, Type } from "class-transformer";

/**
 * A ship
 */
export class Ship extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "cargo" })
    @Type(() => ShipCargo)
    cargo: ShipCargo;

    /**
     * The ship's crew service and maintain the ship's systems and equipment.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "crew" })
    @Type(() => ShipCrew)
    crew: ShipCrew;

    /**
     * The engine determines how quickly a ship travels between waypoints.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "engine" })
    @Type(() => ShipEngine)
    engine: ShipEngine;

    /**
     * The frame of the ship. The frame determines the number of modules and mounting points of the ship, as well as base fuel capacity. As the condition of the frame takes more wear, the ship will become more sluggish and less maneuverable.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "frame" })
    @Type(() => ShipFrame)
    frame: ShipFrame;

    /**
     * Details of the ship's fuel tanks including how much fuel was consumed during the last transit or action.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "fuel" })
    @Type(() => ShipFuel)
    fuel: ShipFuel;

    @SpeakeasyMetadata({ elemType: ShipModule })
    @Expose({ name: "modules" })
    @Type(() => ShipModule)
    modules: ShipModule[];

    @SpeakeasyMetadata({ elemType: ShipMount })
    @Expose({ name: "mounts" })
    @Type(() => ShipMount)
    mounts: ShipMount[];

    /**
     * The navigation information of the ship.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "nav" })
    @Type(() => ShipNav)
    nav: ShipNav;

    /**
     * The reactor of the ship. The reactor is responsible for powering the ship's systems and weapons.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "reactor" })
    @Type(() => ShipReactor)
    reactor: ShipReactor;

    /**
     * The public registration information of the ship
     */
    @SpeakeasyMetadata()
    @Expose({ name: "registration" })
    @Type(() => ShipRegistration)
    registration: ShipRegistration;

    /**
     * The globally unique identifier of the ship in the following format: `[AGENT_SYMBOL]_[HEX_ID]`
     */
    @SpeakeasyMetadata()
    @Expose({ name: "symbol" })
    symbol: string;
}
