/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ShipRequirements } from "./shiprequirements";
import { Expose, Type } from "class-transformer";

export enum ShipEngineSymbol {
    EngineImpulseDriveI = "ENGINE_IMPULSE_DRIVE_I",
    EngineIonDriveI = "ENGINE_ION_DRIVE_I",
    EngineIonDriveIi = "ENGINE_ION_DRIVE_II",
    EngineHyperDriveI = "ENGINE_HYPER_DRIVE_I",
}

/**
 * The engine determines how quickly a ship travels between waypoints.
 */
export class ShipEngine extends SpeakeasyBase {
    /**
     * Condition is a range of 0 to 100 where 0 is completely worn out and 100 is brand new.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "condition" })
    condition?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description: string;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    /**
     * The requirements for installation on a ship
     */
    @SpeakeasyMetadata()
    @Expose({ name: "requirements" })
    @Type(() => ShipRequirements)
    requirements: ShipRequirements;

    @SpeakeasyMetadata()
    @Expose({ name: "speed" })
    speed: number;

    @SpeakeasyMetadata()
    @Expose({ name: "symbol" })
    symbol: ShipEngineSymbol;
}
