/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ShipType } from "./shiptype";
import { ShipyardShip } from "./shipyardship";
import { ShipyardTransaction } from "./shipyardtransaction";
import { Expose, Type } from "class-transformer";

export class ShipyardShipTypes extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type?: ShipType;
}

export class Shipyard extends SpeakeasyBase {
    /**
     * The list of ship types available for purchase at this shipyard.
     */
    @SpeakeasyMetadata({ elemType: ShipyardShipTypes })
    @Expose({ name: "shipTypes" })
    @Type(() => ShipyardShipTypes)
    shipTypes: ShipyardShipTypes[];

    /**
     * The ships that are currently available for purchase at the shipyard.
     */
    @SpeakeasyMetadata({ elemType: ShipyardShip })
    @Expose({ name: "ships" })
    @Type(() => ShipyardShip)
    ships?: ShipyardShip[];

    /**
     * The symbol of the shipyard. The symbol is the same as the waypoint where the shipyard is located.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "symbol" })
    symbol: string;

    /**
     * The list of recent transactions at this shipyard.
     */
    @SpeakeasyMetadata({ elemType: ShipyardTransaction })
    @Expose({ name: "transactions" })
    @Type(() => ShipyardTransaction)
    transactions?: ShipyardTransaction[];
}
