/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Transform, Type } from "class-transformer";

export class ShipFuelConsumed extends SpeakeasyBase {
    /**
     * The amount of fuel consumed by the most recent transit or action.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "amount" })
    amount: number;

    /**
     * The time at which the fuel was consumed.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "timestamp" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    timestamp: Date;
}

/**
 * Details of the ship's fuel tanks including how much fuel was consumed during the last transit or action.
 */
export class ShipFuel extends SpeakeasyBase {
    /**
     * The maximum amount of fuel the ship's tanks can hold.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "capacity" })
    capacity: number;

    @SpeakeasyMetadata()
    @Expose({ name: "consumed" })
    @Type(() => ShipFuelConsumed)
    consumed?: ShipFuelConsumed;

    /**
     * The current amount of fuel in the ship's tanks.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "current" })
    current: number;
}
