/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ShipCargoItem } from "./shipcargoitem";
import { Expose, Type } from "class-transformer";

export class ShipCargo extends SpeakeasyBase {
    /**
     * The max number of items that can be stored in the cargo hold.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "capacity" })
    capacity: number;

    /**
     * The items currently in the cargo hold.
     */
    @SpeakeasyMetadata({ elemType: ShipCargoItem })
    @Expose({ name: "inventory" })
    @Type(() => ShipCargoItem)
    inventory: ShipCargoItem[];

    /**
     * The number of items currently stored in the cargo hold.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "units" })
    units: number;
}
