/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ShipRequirements } from "./shiprequirements";
import { Expose, Type } from "class-transformer";

export enum ShipReactorSymbol {
    ReactorSolarI = "REACTOR_SOLAR_I",
    ReactorFusionI = "REACTOR_FUSION_I",
    ReactorFissionI = "REACTOR_FISSION_I",
    ReactorChemicalI = "REACTOR_CHEMICAL_I",
    ReactorAntimatterI = "REACTOR_ANTIMATTER_I",
}

/**
 * The reactor of the ship. The reactor is responsible for powering the ship's systems and weapons.
 */
export class ShipReactor extends SpeakeasyBase {
    /**
     * Condition is a range of 0 to 100 where 0 is completely worn out and 100 is brand new.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "condition" })
    condition?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description: string;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    @SpeakeasyMetadata()
    @Expose({ name: "powerOutput" })
    powerOutput: number;

    /**
     * The requirements for installation on a ship
     */
    @SpeakeasyMetadata()
    @Expose({ name: "requirements" })
    @Type(() => ShipRequirements)
    requirements: ShipRequirements;

    @SpeakeasyMetadata()
    @Expose({ name: "symbol" })
    symbol: ShipReactorSymbol;
}
