/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ShipNavFlightMode } from "./shipnavflightmode";
import { ShipNavRoute } from "./shipnavroute";
import { ShipNavStatus } from "./shipnavstatus";
import { Expose, Type } from "class-transformer";

/**
 * The navigation information of the ship.
 */
export class ShipNav extends SpeakeasyBase {
    /**
     * The ship's set speed when traveling between waypoints or systems.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "flightMode" })
    flightMode: ShipNavFlightMode;

    /**
     * The routing information for the ship's most recent transit or current location.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "route" })
    @Type(() => ShipNavRoute)
    route: ShipNavRoute;

    /**
     * The current status of the ship
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status: ShipNavStatus;

    /**
     * The system symbol of the ship's current location.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "systemSymbol" })
    systemSymbol: string;

    /**
     * The waypoint symbol of the ship's current location, or if the ship is in-transit, the waypoint symbol of the ship's destination.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "waypointSymbol" })
    waypointSymbol: string;
}
