/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * The rotation of crew shifts. A stricter shift improves the ship's performance. A more relaxed shift improves the crew's morale.
 */
export enum ShipCrewRotation {
    Strict = "STRICT",
    Relaxed = "RELAXED",
}

/**
 * The ship's crew service and maintain the ship's systems and equipment.
 */
export class ShipCrew extends SpeakeasyBase {
    /**
     * The maximum number of crew members the ship can support.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "capacity" })
    capacity: number;

    /**
     * The current number of crew members on the ship.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "current" })
    current: number;

    /**
     * A rough measure of the crew's morale. A higher morale means the crew is happier and more productive. A lower morale means the ship is more prone to accidents.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "morale" })
    morale: number;

    /**
     * The minimum number of crew members required to maintain the ship.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "required" })
    required: number;

    /**
     * The rotation of crew shifts. A stricter shift improves the ship's performance. A more relaxed shift improves the crew's morale.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "rotation" })
    rotation: ShipCrewRotation;

    /**
     * The amount of credits per crew member paid per hour. Wages are paid when a ship docks at a civilized waypoint.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "wages" })
    wages: number;
}
