/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * The current status of the ship
 */
export enum ShipNavStatus {
    InTransit = "IN_TRANSIT",
    InOrbit = "IN_ORBIT",
    Docked = "DOCKED",
}
