/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ShipEngine } from "./shipengine";
import { ShipFrame } from "./shipframe";
import { ShipModule } from "./shipmodule";
import { ShipMount } from "./shipmount";
import { ShipReactor } from "./shipreactor";
import { ShipType } from "./shiptype";
import { Expose, Type } from "class-transformer";

export class ShipyardShip extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description: string;

    /**
     * The engine determines how quickly a ship travels between waypoints.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "engine" })
    @Type(() => ShipEngine)
    engine: ShipEngine;

    /**
     * The frame of the ship. The frame determines the number of modules and mounting points of the ship, as well as base fuel capacity. As the condition of the frame takes more wear, the ship will become more sluggish and less maneuverable.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "frame" })
    @Type(() => ShipFrame)
    frame: ShipFrame;

    @SpeakeasyMetadata({ elemType: ShipModule })
    @Expose({ name: "modules" })
    @Type(() => ShipModule)
    modules: ShipModule[];

    @SpeakeasyMetadata({ elemType: ShipMount })
    @Expose({ name: "mounts" })
    @Type(() => ShipMount)
    mounts: ShipMount[];

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    @SpeakeasyMetadata()
    @Expose({ name: "purchasePrice" })
    purchasePrice: number;

    /**
     * The reactor of the ship. The reactor is responsible for powering the ship's systems and weapons.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "reactor" })
    @Type(() => ShipReactor)
    reactor: ShipReactor;

    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type?: ShipType;
}
