/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * The registered role of the ship
 */
export enum ShipRole {
    Fabricator = "FABRICATOR",
    Harvester = "HARVESTER",
    Hauler = "HAULER",
    Interceptor = "INTERCEPTOR",
    Excavator = "EXCAVATOR",
    Transport = "TRANSPORT",
    Repair = "REPAIR",
    Surveyor = "SURVEYOR",
    Command = "COMMAND",
    Carrier = "CARRIER",
    Patrol = "PATROL",
    Satellite = "SATELLITE",
    Explorer = "EXPLORER",
    Refinery = "REFINERY",
}
