/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ShipRequirements } from "./shiprequirements";
import { Expose, Type } from "class-transformer";

export enum ShipModuleSymbol {
    ModuleMineralProcessorI = "MODULE_MINERAL_PROCESSOR_I",
    ModuleCargoHoldI = "MODULE_CARGO_HOLD_I",
    ModuleCrewQuartersI = "MODULE_CREW_QUARTERS_I",
    ModuleEnvoyQuartersI = "MODULE_ENVOY_QUARTERS_I",
    ModulePassengerCabinI = "MODULE_PASSENGER_CABIN_I",
    ModuleMicroRefineryI = "MODULE_MICRO_REFINERY_I",
    ModuleOreRefineryI = "MODULE_ORE_REFINERY_I",
    ModuleFuelRefineryI = "MODULE_FUEL_REFINERY_I",
    ModuleScienceLabI = "MODULE_SCIENCE_LAB_I",
    ModuleJumpDriveI = "MODULE_JUMP_DRIVE_I",
    ModuleJumpDriveIi = "MODULE_JUMP_DRIVE_II",
    ModuleJumpDriveIii = "MODULE_JUMP_DRIVE_III",
    ModuleWarpDriveI = "MODULE_WARP_DRIVE_I",
    ModuleWarpDriveIi = "MODULE_WARP_DRIVE_II",
    ModuleWarpDriveIii = "MODULE_WARP_DRIVE_III",
    ModuleShieldGeneratorI = "MODULE_SHIELD_GENERATOR_I",
    ModuleShieldGeneratorIi = "MODULE_SHIELD_GENERATOR_II",
}

/**
 * A module can be installed in a ship and provides a set of capabilities such as storage space or quarters for crew. Module installations are permanent.
 */
export class ShipModule extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "capacity" })
    capacity?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    @SpeakeasyMetadata()
    @Expose({ name: "range" })
    range?: number;

    /**
     * The requirements for installation on a ship
     */
    @SpeakeasyMetadata()
    @Expose({ name: "requirements" })
    @Type(() => ShipRequirements)
    requirements: ShipRequirements;

    @SpeakeasyMetadata()
    @Expose({ name: "symbol" })
    symbol: ShipModuleSymbol;
}
