/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * The ship's set speed when traveling between waypoints or systems.
 */
export enum ShipNavFlightMode {
    Drift = "DRIFT",
    Stealth = "STEALTH",
    Cruise = "CRUISE",
    Burn = "BURN",
}
