/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ShipRole } from "./shiprole";
import { Expose } from "class-transformer";

/**
 * The public registration information of the ship
 */
export class ShipRegistration extends SpeakeasyBase {
    /**
     * The symbol of the faction the ship is registered with
     */
    @SpeakeasyMetadata()
    @Expose({ name: "factionSymbol" })
    factionSymbol: string;

    /**
     * The agent's registered name of the ship
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    /**
     * The registered role of the ship
     */
    @SpeakeasyMetadata()
    @Expose({ name: "role" })
    role: ShipRole;
}
