/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Transform } from "class-transformer";

export class ShipyardTransaction extends SpeakeasyBase {
    /**
     * The symbol of the agent that made the transaction.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "agentSymbol" })
    agentSymbol: string;

    /**
     * The price of the transaction.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "price" })
    price: number;

    /**
     * The symbol of the ship that was purchased.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "shipSymbol" })
    shipSymbol: string;

    /**
     * The timestamp of the transaction.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "timestamp" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    timestamp: Date;

    /**
     * The symbol of the waypoint where the transaction took place.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "waypointSymbol" })
    waypointSymbol: string;
}
