/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * The type of cargo item and the number of units.
 */
export class ShipCargoItem extends SpeakeasyBase {
    /**
     * The description of the cargo item type.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description: string;

    /**
     * The name of the cargo item type.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    /**
     * The unique identifier of the cargo item type.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "symbol" })
    symbol: string;

    /**
     * The number of units of the cargo item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "units" })
    units: number;
}
