/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * The requirements for installation on a ship
 */
export class ShipRequirements extends SpeakeasyBase {
    /**
     * The number of crew required for operation.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "crew" })
    crew?: number;

    /**
     * The amount of power required from the reactor.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "power" })
    power?: number;

    /**
     * The number of module slots required for installation.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "slots" })
    slots?: number;
}
