/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum ShipType {
    ShipProbe = "SHIP_PROBE",
    ShipMiningDrone = "SHIP_MINING_DRONE",
    ShipInterceptor = "SHIP_INTERCEPTOR",
    ShipLightHauler = "SHIP_LIGHT_HAULER",
    ShipCommandFrigate = "SHIP_COMMAND_FRIGATE",
    ShipExplorer = "SHIP_EXPLORER",
    ShipHeavyFreighter = "SHIP_HEAVY_FREIGHTER",
    ShipLightShuttle = "SHIP_LIGHT_SHUTTLE",
    ShipOreHound = "SHIP_ORE_HOUND",
    ShipRefiningFreighter = "SHIP_REFINING_FREIGHTER",
}
