/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * A surveyed deposit of a mineral or resource available for extraction.
 */
export class SurveyDeposit extends SpeakeasyBase {
    /**
     * The symbol of the deposit.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "symbol" })
    symbol: string;
}
