/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * The type of waypoint.
 */
export enum SystemType {
    NeutronStar = "NEUTRON_STAR",
    RedStar = "RED_STAR",
    OrangeStar = "ORANGE_STAR",
    BlueStar = "BLUE_STAR",
    YoungStar = "YOUNG_STAR",
    WhiteDwarf = "WHITE_DWARF",
    BlackHole = "BLACK_HOLE",
    Hypergiant = "HYPERGIANT",
    Nebula = "NEBULA",
    Unstable = "UNSTABLE",
}
