/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { SystemFaction } from "./systemfaction";
import { SystemType } from "./systemtype";
import { SystemWaypoint } from "./systemwaypoint";
import { Expose, Type } from "class-transformer";

export class System extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: SystemFaction })
    @Expose({ name: "factions" })
    @Type(() => SystemFaction)
    factions: SystemFaction[];

    @SpeakeasyMetadata()
    @Expose({ name: "sectorSymbol" })
    sectorSymbol: string;

    @SpeakeasyMetadata()
    @Expose({ name: "symbol" })
    symbol: string;

    /**
     * The type of waypoint.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type: SystemType;

    @SpeakeasyMetadata({ elemType: SystemWaypoint })
    @Expose({ name: "waypoints" })
    @Type(() => SystemWaypoint)
    waypoints: SystemWaypoint[];

    @SpeakeasyMetadata()
    @Expose({ name: "x" })
    x: number;

    @SpeakeasyMetadata()
    @Expose({ name: "y" })
    y: number;
}
