/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * The type of waypoint.
 */
export enum WaypointType {
    Planet = "PLANET",
    GasGiant = "GAS_GIANT",
    Moon = "MOON",
    OrbitalStation = "ORBITAL_STATION",
    JumpGate = "JUMP_GATE",
    AsteroidField = "ASTEROID_FIELD",
    Nebula = "NEBULA",
    DebrisField = "DEBRIS_FIELD",
    GravityWell = "GRAVITY_WELL",
}
