/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class AcceptContractSecurity extends SpeakeasyBase {
    @SpeakeasyMetadata({
        data: "security, scheme=true;type=http;subtype=bearer;name=Authorization",
    })
    agentToken: string;
}

export class AcceptContractRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=contractId" })
    contractId: string;
}

export class AcceptContract200ApplicationJSONData extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "agent" })
    @Type(() => shared.Agent)
    agent: shared.Agent;

    @SpeakeasyMetadata()
    @Expose({ name: "contract" })
    @Type(() => shared.Contract)
    contract: shared.Contract;
}

/**
 * OK
 */
export class AcceptContract200ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => AcceptContract200ApplicationJSONData)
    data: AcceptContract200ApplicationJSONData;
}

export class AcceptContractResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * OK
     */
    @SpeakeasyMetadata()
    acceptContract200ApplicationJSONObject?: AcceptContract200ApplicationJSON;
}
