/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class CreateSurveySecurity extends SpeakeasyBase {
    @SpeakeasyMetadata({
        data: "security, scheme=true;type=http;subtype=bearer;name=Authorization",
    })
    agentToken: string;
}

export class CreateSurveyRequest extends SpeakeasyBase {
    /**
     * The symbol of the ship
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=shipSymbol" })
    shipSymbol: string;
}

export class CreateSurvey201ApplicationJSONData extends SpeakeasyBase {
    /**
     * A cooldown is a period of time in which a ship cannot perform certain actions.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "cooldown" })
    @Type(() => shared.Cooldown)
    cooldown: shared.Cooldown;

    @SpeakeasyMetadata({ elemType: shared.Survey })
    @Expose({ name: "surveys" })
    @Type(() => shared.Survey)
    surveys: shared.Survey[];
}

/**
 * Created
 */
export class CreateSurvey201ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => CreateSurvey201ApplicationJSONData)
    data: CreateSurvey201ApplicationJSONData;
}

export class CreateSurveyResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * Created
     */
    @SpeakeasyMetadata()
    createSurvey201ApplicationJSONObject?: CreateSurvey201ApplicationJSON;
}
