/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class CreateShipWaypointScanSecurity extends SpeakeasyBase {
    @SpeakeasyMetadata({
        data: "security, scheme=true;type=http;subtype=bearer;name=Authorization",
    })
    agentToken: string;
}

export class CreateShipWaypointScanRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=shipSymbol" })
    shipSymbol: string;
}

export class CreateShipWaypointScan201ApplicationJSONData extends SpeakeasyBase {
    /**
     * A cooldown is a period of time in which a ship cannot perform certain actions.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "cooldown" })
    @Type(() => shared.Cooldown)
    cooldown: shared.Cooldown;

    @SpeakeasyMetadata({ elemType: shared.ScannedWaypoint })
    @Expose({ name: "waypoints" })
    @Type(() => shared.ScannedWaypoint)
    waypoints: shared.ScannedWaypoint[];
}

/**
 * Created
 */
export class CreateShipWaypointScan201ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => CreateShipWaypointScan201ApplicationJSONData)
    data: CreateShipWaypointScan201ApplicationJSONData;
}

export class CreateShipWaypointScanResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * Created
     */
    @SpeakeasyMetadata()
    createShipWaypointScan201ApplicationJSONObject?: CreateShipWaypointScan201ApplicationJSON;
}
