/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class CreateShipSystemScanSecurity extends SpeakeasyBase {
    @SpeakeasyMetadata({
        data: "security, scheme=true;type=http;subtype=bearer;name=Authorization",
    })
    agentToken: string;
}

export class CreateShipSystemScanRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=shipSymbol" })
    shipSymbol: string;
}

export class CreateShipSystemScan201ApplicationJSONData extends SpeakeasyBase {
    /**
     * A cooldown is a period of time in which a ship cannot perform certain actions.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "cooldown" })
    @Type(() => shared.Cooldown)
    cooldown: shared.Cooldown;

    @SpeakeasyMetadata({ elemType: shared.ScannedSystem })
    @Expose({ name: "systems" })
    @Type(() => shared.ScannedSystem)
    systems: shared.ScannedSystem[];
}

/**
 * Created
 */
export class CreateShipSystemScan201ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => CreateShipSystemScan201ApplicationJSONData)
    data: CreateShipSystemScan201ApplicationJSONData;
}

export class CreateShipSystemScanResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * Created
     */
    @SpeakeasyMetadata()
    createShipSystemScan201ApplicationJSONObject?: CreateShipSystemScan201ApplicationJSON;
}
