/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class DeliverContractSecurity extends SpeakeasyBase {
    @SpeakeasyMetadata({
        data: "security, scheme=true;type=http;subtype=bearer;name=Authorization",
    })
    agentToken: string;
}

export class DeliverContractRequestBody extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "shipSymbol" })
    shipSymbol: string;

    @SpeakeasyMetadata()
    @Expose({ name: "tradeSymbol" })
    tradeSymbol: string;

    @SpeakeasyMetadata()
    @Expose({ name: "units" })
    units: number;
}

export class DeliverContractRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    requestBody?: DeliverContractRequestBody;

    /**
     * The ID of the contract
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=contractId" })
    contractId: string;
}

export class DeliverContract200ApplicationJSONData extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "cargo" })
    @Type(() => shared.ShipCargo)
    cargo: shared.ShipCargo;

    @SpeakeasyMetadata()
    @Expose({ name: "contract" })
    @Type(() => shared.Contract)
    contract: shared.Contract;
}

/**
 * OK
 */
export class DeliverContract200ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => DeliverContract200ApplicationJSONData)
    data: DeliverContract200ApplicationJSONData;
}

export class DeliverContractResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * OK
     */
    @SpeakeasyMetadata()
    deliverContract200ApplicationJSONObject?: DeliverContract200ApplicationJSON;
}
