/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class ExtractResourcesSecurity extends SpeakeasyBase {
    @SpeakeasyMetadata({
        data: "security, scheme=true;type=http;subtype=bearer;name=Authorization",
    })
    agentToken: string;
}

export class ExtractResourcesRequestBody extends SpeakeasyBase {
    /**
     * A resource survey of a waypoint, detailing a specific extraction location and the types of resources that can be found there.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "survey" })
    @Type(() => shared.Survey)
    survey?: shared.Survey;
}

export class ExtractResourcesRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    requestBody?: ExtractResourcesRequestBody;

    /**
     * The ship symbol
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=shipSymbol" })
    shipSymbol: string;
}

export class ExtractResources201ApplicationJSONData extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "cargo" })
    @Type(() => shared.ShipCargo)
    cargo: shared.ShipCargo;

    /**
     * A cooldown is a period of time in which a ship cannot perform certain actions.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "cooldown" })
    @Type(() => shared.Cooldown)
    cooldown: shared.Cooldown;

    @SpeakeasyMetadata()
    @Expose({ name: "extraction" })
    @Type(() => shared.Extraction)
    extraction: shared.Extraction;
}

/**
 * Created
 */
export class ExtractResources201ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => ExtractResources201ApplicationJSONData)
    data: ExtractResources201ApplicationJSONData;
}

export class ExtractResourcesResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * Created
     */
    @SpeakeasyMetadata()
    extractResources201ApplicationJSONObject?: ExtractResources201ApplicationJSON;
}
