/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class GetFactionRequest extends SpeakeasyBase {
    /**
     * The faction symbol
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=factionSymbol" })
    factionSymbol: string;
}

/**
 * OK
 */
export class GetFaction200ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => shared.Faction)
    data: shared.Faction;
}

export class GetFactionResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * OK
     */
    @SpeakeasyMetadata()
    getFaction200ApplicationJSONObject?: GetFaction200ApplicationJSON;
}
