/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class GetJumpGateRequest extends SpeakeasyBase {
    /**
     * The system symbol
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=systemSymbol" })
    systemSymbol: string;

    /**
     * The waypoint symbol
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=waypointSymbol" })
    waypointSymbol: string;
}

/**
 * OK
 */
export class GetJumpGate200ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => shared.JumpGate)
    data: shared.JumpGate;
}

export class GetJumpGateResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * OK
     */
    @SpeakeasyMetadata()
    getJumpGate200ApplicationJSONObject?: GetJumpGate200ApplicationJSON;
}
