/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class GetSystemRequest extends SpeakeasyBase {
    /**
     * The system symbol
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=systemSymbol" })
    systemSymbol: string;
}

/**
 * OK
 */
export class GetSystem200ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => shared.System)
    data: shared.System;
}

export class GetSystemResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * OK
     */
    @SpeakeasyMetadata()
    getSystem200ApplicationJSONObject?: GetSystem200ApplicationJSON;
}
