/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class GetStatus200ApplicationJSONAnnouncements extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "body" })
    body: string;

    @SpeakeasyMetadata()
    @Expose({ name: "title" })
    title: string;
}

export class GetStatus200ApplicationJSONLeaderboardsMostCredits extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "agentSymbol" })
    agentSymbol: string;

    @SpeakeasyMetadata()
    @Expose({ name: "credits" })
    credits: number;
}

export class GetStatus200ApplicationJSONLeaderboardsMostSubmittedCharts extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "agentSymbol" })
    agentSymbol: string;

    @SpeakeasyMetadata()
    @Expose({ name: "chartCount" })
    chartCount: number;
}

export class GetStatus200ApplicationJSONLeaderboards extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: GetStatus200ApplicationJSONLeaderboardsMostCredits })
    @Expose({ name: "mostCredits" })
    @Type(() => GetStatus200ApplicationJSONLeaderboardsMostCredits)
    mostCredits: GetStatus200ApplicationJSONLeaderboardsMostCredits[];

    @SpeakeasyMetadata({ elemType: GetStatus200ApplicationJSONLeaderboardsMostSubmittedCharts })
    @Expose({ name: "mostSubmittedCharts" })
    @Type(() => GetStatus200ApplicationJSONLeaderboardsMostSubmittedCharts)
    mostSubmittedCharts: GetStatus200ApplicationJSONLeaderboardsMostSubmittedCharts[];
}

export class GetStatus200ApplicationJSONLinks extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    @SpeakeasyMetadata()
    @Expose({ name: "url" })
    url: string;
}

export class GetStatus200ApplicationJSONServerResets extends SpeakeasyBase {
    /**
     * How often we intend to reset the game server.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "frequency" })
    frequency: string;

    /**
     * The date and time when the game server will reset.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "next" })
    next: string;
}

export class GetStatus200ApplicationJSONStats extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "agents" })
    agents: number;

    @SpeakeasyMetadata()
    @Expose({ name: "ships" })
    ships: number;

    @SpeakeasyMetadata()
    @Expose({ name: "systems" })
    systems: number;

    @SpeakeasyMetadata()
    @Expose({ name: "waypoints" })
    waypoints: number;
}

/**
 * OK
 */
export class GetStatus200ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: GetStatus200ApplicationJSONAnnouncements })
    @Expose({ name: "announcements" })
    @Type(() => GetStatus200ApplicationJSONAnnouncements)
    announcements: GetStatus200ApplicationJSONAnnouncements[];

    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description: string;

    @SpeakeasyMetadata()
    @Expose({ name: "leaderboards" })
    @Type(() => GetStatus200ApplicationJSONLeaderboards)
    leaderboards: GetStatus200ApplicationJSONLeaderboards;

    @SpeakeasyMetadata({ elemType: GetStatus200ApplicationJSONLinks })
    @Expose({ name: "links" })
    @Type(() => GetStatus200ApplicationJSONLinks)
    links: GetStatus200ApplicationJSONLinks[];

    /**
     * The date and time when the game server was last reset.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "resetDate" })
    resetDate: string;

    @SpeakeasyMetadata()
    @Expose({ name: "serverResets" })
    @Type(() => GetStatus200ApplicationJSONServerResets)
    serverResets: GetStatus200ApplicationJSONServerResets;

    @SpeakeasyMetadata()
    @Expose({ name: "stats" })
    @Type(() => GetStatus200ApplicationJSONStats)
    stats: GetStatus200ApplicationJSONStats;

    /**
     * The current status of the game server.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status: string;

    /**
     * The current version of the API.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "version" })
    version: string;
}

export class GetStatusResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * OK
     */
    @SpeakeasyMetadata()
    getStatus200ApplicationJSONObject?: GetStatus200ApplicationJSON;
}
