/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class GetWaypointRequest extends SpeakeasyBase {
    /**
     * The system symbol
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=systemSymbol" })
    systemSymbol: string;

    /**
     * The waypoint symbol
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=waypointSymbol" })
    waypointSymbol: string;
}

/**
 * OK
 */
export class GetWaypoint200ApplicationJSON extends SpeakeasyBase {
    /**
     * A waypoint is a location that ships can travel to such as a Planet, Moon or Space Station.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => shared.Waypoint)
    data: shared.Waypoint;
}

export class GetWaypointResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * OK
     */
    @SpeakeasyMetadata()
    getWaypoint200ApplicationJSONObject?: GetWaypoint200ApplicationJSON;
}
