/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class JumpShipSecurity extends SpeakeasyBase {
    @SpeakeasyMetadata({
        data: "security, scheme=true;type=http;subtype=bearer;name=Authorization",
    })
    agentToken: string;
}

export class JumpShipRequestBody extends SpeakeasyBase {
    /**
     * The system symbol to jump to.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "systemSymbol" })
    systemSymbol: string;
}

export class JumpShipRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    requestBody?: JumpShipRequestBody;

    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=shipSymbol" })
    shipSymbol: string;
}

export class JumpShip200ApplicationJSONData extends SpeakeasyBase {
    /**
     * A cooldown is a period of time in which a ship cannot perform certain actions.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "cooldown" })
    @Type(() => shared.Cooldown)
    cooldown: shared.Cooldown;

    /**
     * The navigation information of the ship.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "nav" })
    @Type(() => shared.ShipNav)
    nav?: shared.ShipNav;
}

/**
 * OK
 */
export class JumpShip200ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => JumpShip200ApplicationJSONData)
    data: JumpShip200ApplicationJSONData;
}

export class JumpShipResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * OK
     */
    @SpeakeasyMetadata()
    jumpShip200ApplicationJSONObject?: JumpShip200ApplicationJSON;
}
