/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class NavigateShipSecurity extends SpeakeasyBase {
    @SpeakeasyMetadata({
        data: "security, scheme=true;type=http;subtype=bearer;name=Authorization",
    })
    agentToken: string;
}

export class NavigateShipRequestBody extends SpeakeasyBase {
    /**
     * The target destination.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "waypointSymbol" })
    waypointSymbol: string;
}

export class NavigateShipRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    requestBody?: NavigateShipRequestBody;

    /**
     * The ship symbol
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=shipSymbol" })
    shipSymbol: string;
}

export class NavigateShip200ApplicationJSONData extends SpeakeasyBase {
    /**
     * Details of the ship's fuel tanks including how much fuel was consumed during the last transit or action.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "fuel" })
    @Type(() => shared.ShipFuel)
    fuel: shared.ShipFuel;

    /**
     * The navigation information of the ship.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "nav" })
    @Type(() => shared.ShipNav)
    nav: shared.ShipNav;
}

/**
 * The successful transit information including the route details and changes to ship fuel, supplies, and crew wages paid. The route includes the expected time of arrival.
 */
export class NavigateShip200ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => NavigateShip200ApplicationJSONData)
    data: NavigateShip200ApplicationJSONData;
}

export class NavigateShipResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * The successful transit information including the route details and changes to ship fuel, supplies, and crew wages paid. The route includes the expected time of arrival.
     */
    @SpeakeasyMetadata()
    navigateShip200ApplicationJSONObject?: NavigateShip200ApplicationJSON;
}
