/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class OrbitShipSecurity extends SpeakeasyBase {
    @SpeakeasyMetadata({
        data: "security, scheme=true;type=http;subtype=bearer;name=Authorization",
    })
    agentToken: string;
}

export class OrbitShipRequest extends SpeakeasyBase {
    /**
     * The symbol of the ship
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=shipSymbol" })
    shipSymbol: string;
}

export class OrbitShipOrbitShip200ResponseData extends SpeakeasyBase {
    /**
     * The navigation information of the ship.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "nav" })
    @Type(() => shared.ShipNav)
    nav: shared.ShipNav;
}

/**
 * The ship has successfully moved into orbit at it's current location.
 */
export class OrbitShipOrbitShip200Response extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => OrbitShipOrbitShip200ResponseData)
    data: OrbitShipOrbitShip200ResponseData;
}

export class OrbitShipResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * The ship has successfully moved into orbit at it's current location.
     */
    @SpeakeasyMetadata()
    orbitShip200Response?: OrbitShipOrbitShip200Response;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
