/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class PatchShipNavSecurity extends SpeakeasyBase {
    @SpeakeasyMetadata({
        data: "security, scheme=true;type=http;subtype=bearer;name=Authorization",
    })
    agentToken: string;
}

export class PatchShipNavRequestBody extends SpeakeasyBase {
    /**
     * The ship's set speed when traveling between waypoints or systems.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "flightMode" })
    flightMode?: shared.ShipNavFlightMode;
}

export class PatchShipNavRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    requestBody?: PatchShipNavRequestBody;

    /**
     * The ship symbol
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=shipSymbol" })
    shipSymbol: string;
}

/**
 * The updated nav status of the ship.
 */
export class PatchShipNav200ApplicationJSON extends SpeakeasyBase {
    /**
     * The navigation information of the ship.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => shared.ShipNav)
    data: shared.ShipNav;
}

export class PatchShipNavResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * The updated nav status of the ship.
     */
    @SpeakeasyMetadata()
    patchShipNav200ApplicationJSONObject?: PatchShipNav200ApplicationJSON;
}
