/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class PurchaseShipSecurity extends SpeakeasyBase {
    @SpeakeasyMetadata({
        data: "security, scheme=true;type=http;subtype=bearer;name=Authorization",
    })
    agentToken: string;
}

export class PurchaseShipRequestBody extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "shipType" })
    shipType: shared.ShipType;

    /**
     * The symbol of the waypoint you want to purchase the ship at.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "waypointSymbol" })
    waypointSymbol: string;
}

export class PurchaseShip201ApplicationJSONData extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "agent" })
    @Type(() => shared.Agent)
    agent: shared.Agent;

    /**
     * A ship
     */
    @SpeakeasyMetadata()
    @Expose({ name: "ship" })
    @Type(() => shared.Ship)
    ship: shared.Ship;

    @SpeakeasyMetadata()
    @Expose({ name: "transaction" })
    @Type(() => shared.ShipyardTransaction)
    transaction: shared.ShipyardTransaction;
}

/**
 * Created
 */
export class PurchaseShip201ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => PurchaseShip201ApplicationJSONData)
    data: PurchaseShip201ApplicationJSONData;
}

export class PurchaseShipResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * Created
     */
    @SpeakeasyMetadata()
    purchaseShip201ApplicationJSONObject?: PurchaseShip201ApplicationJSON;
}
