/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

/**
 * The faction you choose determines your headquarters.
 */
export enum RegisterRequestBodyFaction {
    Cosmic = "COSMIC",
    Void = "VOID",
    Galactic = "GALACTIC",
    Quantum = "QUANTUM",
    Dominion = "DOMINION",
}

export class RegisterRequestBody extends SpeakeasyBase {
    /**
     * Your email address. This is used if you reserved your call sign between resets.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "email" })
    email?: string;

    /**
     * The faction you choose determines your headquarters.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "faction" })
    faction: RegisterRequestBodyFaction;

    /**
     * How other agents will see your ships and information.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "symbol" })
    symbol: string;
}

export class Register201ApplicationJSONData extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "agent" })
    @Type(() => shared.Agent)
    agent: shared.Agent;

    @SpeakeasyMetadata()
    @Expose({ name: "contract" })
    @Type(() => shared.Contract)
    contract: shared.Contract;

    @SpeakeasyMetadata()
    @Expose({ name: "faction" })
    @Type(() => shared.Faction)
    faction: shared.Faction;

    /**
     * A ship
     */
    @SpeakeasyMetadata()
    @Expose({ name: "ship" })
    @Type(() => shared.Ship)
    ship: shared.Ship;

    /**
     * A Bearer token for accessing secured API endpoints.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "token" })
    token: string;
}

/**
 * OK
 */
export class Register201ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => Register201ApplicationJSONData)
    data: Register201ApplicationJSONData;
}

export class RegisterResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * OK
     */
    @SpeakeasyMetadata()
    register201ApplicationJSONObject?: Register201ApplicationJSON;
}
