/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class SellCargoSecurity extends SpeakeasyBase {
    @SpeakeasyMetadata({
        data: "security, scheme=true;type=http;subtype=bearer;name=Authorization",
    })
    agentToken: string;
}

export class SellCargoSellCargoRequest extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "symbol" })
    symbol: string;

    @SpeakeasyMetadata()
    @Expose({ name: "units" })
    units: number;
}

export class SellCargoRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    requestBody?: SellCargoSellCargoRequest;

    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=shipSymbol" })
    shipSymbol: string;
}

export class SellCargoSellCargo201ResponseData extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "agent" })
    @Type(() => shared.Agent)
    agent: shared.Agent;

    @SpeakeasyMetadata()
    @Expose({ name: "cargo" })
    @Type(() => shared.ShipCargo)
    cargo: shared.ShipCargo;

    @SpeakeasyMetadata()
    @Expose({ name: "transaction" })
    @Type(() => shared.MarketTransaction)
    transaction: shared.MarketTransaction;
}

/**
 * Created
 */
export class SellCargoSellCargo201Response extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => SellCargoSellCargo201ResponseData)
    data: SellCargoSellCargo201ResponseData;
}

export class SellCargoResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * Created
     */
    @SpeakeasyMetadata()
    sellCargo201Response?: SellCargoSellCargo201Response;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
